### ISSUE TITLE
How to use with TextField?

### ISSUE THREAD

**Issue by klaszlo8207** [tomwyr/positioned-tap-detector#3]

**Comment by tomwyr** [comment]
Unfortunately, `TextField` makes it a bit tricky to catch tap events, this is what the documentation says:

> Handling some of those events by wrapping the text field with a competing GestureDetector is problematic.

The only way I was able to make it work was by wrapping `TextField` with `AbsorbPointer` (so that tap events are properly delivered to `PositionedTapDetector`) but then you need to request focus on the text input manually:

```Dart
PositionedTapDetector(
  onTap: _onTapPosition,
  onLongPress: (_) => _focusNode.requestFocus(),
  child: AbsorbPointer(
    child: TextField(focusNode: _focusNode),
  ),
)
```
